# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c58b4d565c2014c9127ebc1dc516f94372cd893d0c58c25d545a8c9099f519faccfef8631738f7c9415f1aa005fdfa7b769746b4ace4bdde566850738678395e

test:
  secret_key_base: 3fa5db360507f3593be324f2215a2d8154e3b6aae853f946808f1b1e48bac40aecfe403ded48502be9eb13c07122e02430233ef6fec7fc13d9ae4d04d2996285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
